#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
homepage:
    path: /{_locale}
    controller: App\Controller\DefaultController::homepage
    requirements:
      _locale: '%app_locales%'
    defaults:
      template: default/homepage.html.twig
      _locale: '%locale%'
